-- Create admin user for KDR Tech Admin Dashboard
-- This will create an admin user that can access the /admin panel

-- SECURITY: this file previously documented a real, working admin email +
-- password pair as an example. That was committed to a public repo and must
-- be treated as compromised — rotate that account's password immediately if
-- you haven't already (Supabase Dashboard → Authentication → Users → select
-- the user → Reset password), regardless of whether it's still in use.

-- Admin users are managed entirely through Supabase Auth, not via SQL insert
-- into auth.users. To create one:
--
-- 1. Go to your Supabase Dashboard → Authentication → Users
-- 2. Click "Add user"
-- 3. Enter the admin's real email address
-- 4. Generate a strong, unique password at creation time (a password
--    manager's generator is fine) — do not write it down in this repo
-- 5. Check "Auto Confirm User" so the account is immediately active
-- 6. Share the password with the admin out-of-band (not via this repo,
--    not via chat/email in plaintext) and have them change it on first login
-- 7. Enable MFA (TOTP) for the account under Authentication → Users
--
-- After creating the user, they can log in at: /admin/login
--
-- Note: this SQL file is documentation only — Supabase Auth users cannot be
-- created via direct SQL insert into auth.users.
